[tool.poetry]
name = "cli"
version = "0.1.0"
description = "Use Pydantic models to create React components from popular libraries."
authors = ["Ryan Partridge <rpartridge101@yahoo.co.uk>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.scripts]
zentra = "cli.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.3"
pydantic = "2.7"
beautifulsoup4 = "^4.12.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.12"
hypothesis = "^6.98.17"
pytest-cov = "^4.1.0"
mike = "^2.0.0"
mkdocstrings = "^0.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
