[tool.poetry]
name = "cli"
version = "0.1.0"
description = "Use Pydantic models to create React components from popular libraries."
authors = ["Ryan Partridge <rpartridge101@yahoo.co.uk>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.scripts]
zentra = "cli.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = { extras = ["all"], version = "^0.9.0" }


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
