BTN_VALID_TEXT_CONTENT = [
    "<Button disabled>\ntest {tag}\n</Button>",
    "<Button>\ntest {tag}\n</Button>",
    '<Button size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button size="sm">\ntest {tag}\n</Button>',
    '<Button size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button size="lg">\ntest {tag}\n</Button>',
    '<Button size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button size="icon">\ntest {tag}\n</Button>',
    '<Button variant="secondary" disabled>\ntest {tag}\n</Button>',
    '<Button variant="secondary">\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="sm">\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="lg">\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="icon">\ntest {tag}\n</Button>',
    '<Button variant="destructive" disabled>\ntest {tag}\n</Button>',
    '<Button variant="destructive">\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="sm">\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="lg">\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="icon">\ntest {tag}\n</Button>',
    '<Button variant="outline" disabled>\ntest {tag}\n</Button>',
    '<Button variant="outline">\ntest {tag}\n</Button>',
    '<Button variant="outline" size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button variant="outline" size="sm">\ntest {tag}\n</Button>',
    '<Button variant="outline" size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button variant="outline" size="lg">\ntest {tag}\n</Button>',
    '<Button variant="outline" size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button variant="outline" size="icon">\ntest {tag}\n</Button>',
    '<Button variant="ghost" disabled>\ntest {tag}\n</Button>',
    '<Button variant="ghost">\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="sm">\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="lg">\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="icon">\ntest {tag}\n</Button>',
    '<Button variant="link" disabled>\ntest {tag}\n</Button>',
    '<Button variant="link">\ntest {tag}\n</Button>',
    '<Button variant="link" size="sm" disabled>\ntest {tag}\n</Button>',
    '<Button variant="link" size="sm">\ntest {tag}\n</Button>',
    '<Button variant="link" size="lg" disabled>\ntest {tag}\n</Button>',
    '<Button variant="link" size="lg">\ntest {tag}\n</Button>',
    '<Button variant="link" size="icon" disabled>\ntest {tag}\n</Button>',
    '<Button variant="link" size="icon">\ntest {tag}\n</Button>',
]

BTN_VALID_ICON_CONTENT = [
    '<Button disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="secondary" size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="destructive" size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="outline" size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="ghost" size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="sm" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="sm">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="lg" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="lg">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="icon" disabled>\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
    '<Button variant="link" size="icon">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Button>',
]

BTN_VALID_TEXT_URL_CONTENT = [
    '<Button asChild disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="icon" disabled>\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="icon">\n<Link href="https://example.com/">\ntest {tag}\n</Link>\n</Button>',
]

BTN_VALID_ICON_URL_CONTENT = [
    '<Button asChild disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="icon" disabled>\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
    '<Button asChild variant="link" size="icon">\n<Link href="https://example.com/">\n<Italic className="mr-2 h-4 w-4" />\ntest {tag}\n</Link>\n</Button>',
]

BTN_VALID_VALS_MAP = {
    "text": BTN_VALID_TEXT_CONTENT,
    "icon": BTN_VALID_ICON_CONTENT,
    "text_url": BTN_VALID_TEXT_URL_CONTENT,
    "icon_url": BTN_VALID_ICON_URL_CONTENT,
}
