BTN_VALID_ATTRS = [
    "asChild disabled",
    "asChild",
    'asChild size="sm" disabled',
    'asChild size="sm"',
    'asChild size="lg" disabled',
    'asChild size="lg"',
    'asChild variant="secondary" disabled',
    'asChild variant="secondary"',
    'asChild variant="secondary" size="sm" disabled',
    'asChild variant="secondary" size="sm"',
    'asChild variant="secondary" size="lg" disabled',
    'asChild variant="secondary" size="lg"',
    'asChild variant="destructive" disabled',
    'asChild variant="destructive"',
    'asChild variant="destructive" size="sm" disabled',
    'asChild variant="destructive" size="sm"',
    'asChild variant="destructive" size="lg" disabled',
    'asChild variant="destructive" size="lg"',
    'asChild variant="outline" disabled',
    'asChild variant="outline"',
    'asChild variant="outline" size="sm" disabled',
    'asChild variant="outline" size="sm"',
    'asChild variant="outline" size="lg" disabled',
    'asChild variant="outline" size="lg"',
    'asChild variant="ghost" disabled',
    'asChild variant="ghost"',
    'asChild variant="ghost" size="sm" disabled',
    'asChild variant="ghost" size="sm"',
    'asChild variant="ghost" size="lg" disabled',
    'asChild variant="ghost" size="lg"',
    'asChild variant="link" disabled',
    'asChild variant="link"',
    'asChild variant="link" size="sm" disabled',
    'asChild variant="link" size="sm"',
    'asChild variant="link" size="lg" disabled',
    'asChild variant="link" size="lg"',
]

ICON_BTN_VALID_ATTRS = [
    "asChild disabled",
    "asChild",
    'asChild size="sm" disabled',
    'asChild size="sm"',
    'asChild size="lg" disabled',
    'asChild size="lg"',
    'asChild variant="secondary" disabled',
    'asChild variant="secondary"',
    'asChild variant="secondary" size="sm" disabled',
    'asChild variant="secondary" size="sm"',
    'asChild variant="secondary" size="lg" disabled',
    'asChild variant="secondary" size="lg"',
    'asChild variant="destructive" disabled',
    'asChild variant="destructive"',
    'asChild variant="destructive" size="sm" disabled',
    'asChild variant="destructive" size="sm"',
    'asChild variant="destructive" size="lg" disabled',
    'asChild variant="destructive" size="lg"',
    'asChild variant="outline" disabled',
    'asChild variant="outline"',
    'asChild variant="outline" size="sm" disabled',
    'asChild variant="outline" size="sm"',
    'asChild variant="outline" size="lg" disabled',
    'asChild variant="outline" size="lg"',
    'asChild variant="ghost" disabled',
    'asChild variant="ghost"',
    'asChild variant="ghost" size="sm" disabled',
    'asChild variant="ghost" size="sm"',
    'asChild variant="ghost" size="lg" disabled',
    'asChild variant="ghost" size="lg"',
    'asChild variant="link" disabled',
    'asChild variant="link"',
    'asChild variant="link" size="sm" disabled',
    'asChild variant="link" size="sm"',
    'asChild variant="link" size="lg" disabled',
    'asChild variant="link" size="lg"',
    "asChild disabled",
    "asChild",
    'asChild size="sm" disabled',
    'asChild size="sm"',
    'asChild size="lg" disabled',
    'asChild size="lg"',
    'asChild variant="secondary" disabled',
    'asChild variant="secondary"',
    'asChild variant="secondary" size="sm" disabled',
    'asChild variant="secondary" size="sm"',
    'asChild variant="secondary" size="lg" disabled',
    'asChild variant="secondary" size="lg"',
    'asChild variant="destructive" disabled',
    'asChild variant="destructive"',
    'asChild variant="destructive" size="sm" disabled',
    'asChild variant="destructive" size="sm"',
    'asChild variant="destructive" size="lg" disabled',
    'asChild variant="destructive" size="lg"',
    'asChild variant="outline" disabled',
    'asChild variant="outline"',
    'asChild variant="outline" size="sm" disabled',
    'asChild variant="outline" size="sm"',
    'asChild variant="outline" size="lg" disabled',
    'asChild variant="outline" size="lg"',
    'asChild variant="ghost" disabled',
    'asChild variant="ghost"',
    'asChild variant="ghost" size="sm" disabled',
    'asChild variant="ghost" size="sm"',
    'asChild variant="ghost" size="lg" disabled',
    'asChild variant="ghost" size="lg"',
    'asChild variant="link" disabled',
    'asChild variant="link"',
    'asChild variant="link" size="sm" disabled',
    'asChild variant="link" size="sm"',
    'asChild variant="link" size="lg" disabled',
    'asChild variant="link" size="lg"',
]
