BTN_VALID_ATTRS = [
    ' disabled href="https://example.com/"',
    ' href="https://example.com/"',
    ' disabled href="https://example.com/" size="sm"',
    ' href="https://example.com/" size="sm"',
    ' disabled href="https://example.com/" size="lg"',
    ' href="https://example.com/" size="lg"',
    ' disabled href="https://example.com/" variant="secondary"',
    ' href="https://example.com/" variant="secondary"',
    ' disabled href="https://example.com/" variant="secondary" size="sm"',
    ' href="https://example.com/" variant="secondary" size="sm"',
    ' disabled href="https://example.com/" variant="secondary" size="lg"',
    ' href="https://example.com/" variant="secondary" size="lg"',
    ' disabled href="https://example.com/" variant="destructive"',
    ' href="https://example.com/" variant="destructive"',
    ' disabled href="https://example.com/" variant="destructive" size="sm"',
    ' href="https://example.com/" variant="destructive" size="sm"',
    ' disabled href="https://example.com/" variant="destructive" size="lg"',
    ' href="https://example.com/" variant="destructive" size="lg"',
    ' disabled href="https://example.com/" variant="outline"',
    ' href="https://example.com/" variant="outline"',
    ' disabled href="https://example.com/" variant="outline" size="sm"',
    ' href="https://example.com/" variant="outline" size="sm"',
    ' disabled href="https://example.com/" variant="outline" size="lg"',
    ' href="https://example.com/" variant="outline" size="lg"',
    ' disabled href="https://example.com/" variant="ghost"',
    ' href="https://example.com/" variant="ghost"',
    ' disabled href="https://example.com/" variant="ghost" size="sm"',
    ' href="https://example.com/" variant="ghost" size="sm"',
    ' disabled href="https://example.com/" variant="ghost" size="lg"',
    ' href="https://example.com/" variant="ghost" size="lg"',
    ' disabled href="https://example.com/" variant="link"',
    ' href="https://example.com/" variant="link"',
    ' disabled href="https://example.com/" variant="link" size="sm"',
    ' href="https://example.com/" variant="link" size="sm"',
    ' disabled href="https://example.com/" variant="link" size="lg"',
    ' href="https://example.com/" variant="link" size="lg"',
]

ICON_BTN_VALID_ATTRS = [
    ' disabled href="https://example.com/"',
    ' href="https://example.com/"',
    ' disabled href="https://example.com/" size="sm"',
    ' href="https://example.com/" size="sm"',
    ' disabled href="https://example.com/" size="lg"',
    ' href="https://example.com/" size="lg"',
    ' disabled href="https://example.com/" variant="secondary"',
    ' href="https://example.com/" variant="secondary"',
    ' disabled href="https://example.com/" variant="secondary" size="sm"',
    ' href="https://example.com/" variant="secondary" size="sm"',
    ' disabled href="https://example.com/" variant="secondary" size="lg"',
    ' href="https://example.com/" variant="secondary" size="lg"',
    ' disabled href="https://example.com/" variant="destructive"',
    ' href="https://example.com/" variant="destructive"',
    ' disabled href="https://example.com/" variant="destructive" size="sm"',
    ' href="https://example.com/" variant="destructive" size="sm"',
    ' disabled href="https://example.com/" variant="destructive" size="lg"',
    ' href="https://example.com/" variant="destructive" size="lg"',
    ' disabled href="https://example.com/" variant="outline"',
    ' href="https://example.com/" variant="outline"',
    ' disabled href="https://example.com/" variant="outline" size="sm"',
    ' href="https://example.com/" variant="outline" size="sm"',
    ' disabled href="https://example.com/" variant="outline" size="lg"',
    ' href="https://example.com/" variant="outline" size="lg"',
    ' disabled href="https://example.com/" variant="ghost"',
    ' href="https://example.com/" variant="ghost"',
    ' disabled href="https://example.com/" variant="ghost" size="sm"',
    ' href="https://example.com/" variant="ghost" size="sm"',
    ' disabled href="https://example.com/" variant="ghost" size="lg"',
    ' href="https://example.com/" variant="ghost" size="lg"',
    ' disabled href="https://example.com/" variant="link"',
    ' href="https://example.com/" variant="link"',
    ' disabled href="https://example.com/" variant="link" size="sm"',
    ' href="https://example.com/" variant="link" size="sm"',
    ' disabled href="https://example.com/" variant="link" size="lg"',
    ' href="https://example.com/" variant="link" size="lg"',
    ' disabled href="https://example.com/"',
    ' href="https://example.com/"',
    ' disabled href="https://example.com/" size="sm"',
    ' href="https://example.com/" size="sm"',
    ' disabled href="https://example.com/" size="lg"',
    ' href="https://example.com/" size="lg"',
    ' disabled href="https://example.com/" variant="secondary"',
    ' href="https://example.com/" variant="secondary"',
    ' disabled href="https://example.com/" variant="secondary" size="sm"',
    ' href="https://example.com/" variant="secondary" size="sm"',
    ' disabled href="https://example.com/" variant="secondary" size="lg"',
    ' href="https://example.com/" variant="secondary" size="lg"',
    ' disabled href="https://example.com/" variant="destructive"',
    ' href="https://example.com/" variant="destructive"',
    ' disabled href="https://example.com/" variant="destructive" size="sm"',
    ' href="https://example.com/" variant="destructive" size="sm"',
    ' disabled href="https://example.com/" variant="destructive" size="lg"',
    ' href="https://example.com/" variant="destructive" size="lg"',
    ' disabled href="https://example.com/" variant="outline"',
    ' href="https://example.com/" variant="outline"',
    ' disabled href="https://example.com/" variant="outline" size="sm"',
    ' href="https://example.com/" variant="outline" size="sm"',
    ' disabled href="https://example.com/" variant="outline" size="lg"',
    ' href="https://example.com/" variant="outline" size="lg"',
    ' disabled href="https://example.com/" variant="ghost"',
    ' href="https://example.com/" variant="ghost"',
    ' disabled href="https://example.com/" variant="ghost" size="sm"',
    ' href="https://example.com/" variant="ghost" size="sm"',
    ' disabled href="https://example.com/" variant="ghost" size="lg"',
    ' href="https://example.com/" variant="ghost" size="lg"',
    ' disabled href="https://example.com/" variant="link"',
    ' href="https://example.com/" variant="link"',
    ' disabled href="https://example.com/" variant="link" size="sm"',
    ' href="https://example.com/" variant="link" size="sm"',
    ' disabled href="https://example.com/" variant="link" size="lg"',
    ' href="https://example.com/" variant="link" size="lg"',
]
