BTN_VALID_CONTENT_WITH_LINK = [
    '<Button asChild disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg">\n<Link href="https://example.com/">\ntest\n</Link>\n</Button>',
]

BTN_VALID_CONTENT_WITHOUT_LINK = [
    "<Button disabled>\ntest\n</Button>",
    "<Button >\ntest\n</Button>",
    '<Button size="sm" disabled>\ntest\n</Button>',
    '<Button size="sm">\ntest\n</Button>',
    '<Button size="lg" disabled>\ntest\n</Button>',
    '<Button size="lg">\ntest\n</Button>',
    '<Button variant="secondary" disabled>\ntest\n</Button>',
    '<Button variant="secondary">\ntest\n</Button>',
    '<Button variant="secondary" size="sm" disabled>\ntest\n</Button>',
    '<Button variant="secondary" size="sm">\ntest\n</Button>',
    '<Button variant="secondary" size="lg" disabled>\ntest\n</Button>',
    '<Button variant="secondary" size="lg">\ntest\n</Button>',
    '<Button variant="destructive" disabled>\ntest\n</Button>',
    '<Button variant="destructive">\ntest\n</Button>',
    '<Button variant="destructive" size="sm" disabled>\ntest\n</Button>',
    '<Button variant="destructive" size="sm">\ntest\n</Button>',
    '<Button variant="destructive" size="lg" disabled>\ntest\n</Button>',
    '<Button variant="destructive" size="lg">\ntest\n</Button>',
    '<Button variant="outline" disabled>\ntest\n</Button>',
    '<Button variant="outline">\ntest\n</Button>',
    '<Button variant="outline" size="sm" disabled>\ntest\n</Button>',
    '<Button variant="outline" size="sm">\ntest\n</Button>',
    '<Button variant="outline" size="lg" disabled>\ntest\n</Button>',
    '<Button variant="outline" size="lg">\ntest\n</Button>',
    '<Button variant="ghost" disabled>\ntest\n</Button>',
    '<Button variant="ghost">\ntest\n</Button>',
    '<Button variant="ghost" size="sm" disabled>\ntest\n</Button>',
    '<Button variant="ghost" size="sm">\ntest\n</Button>',
    '<Button variant="ghost" size="lg" disabled>\ntest\n</Button>',
    '<Button variant="ghost" size="lg">\ntest\n</Button>',
    '<Button variant="link" disabled>\ntest\n</Button>',
    '<Button variant="link">\ntest\n</Button>',
    '<Button variant="link" size="sm" disabled>\ntest\n</Button>',
    '<Button variant="link" size="sm">\ntest\n</Button>',
    '<Button variant="link" size="lg" disabled>\ntest\n</Button>',
    '<Button variant="link" size="lg">\ntest\n</Button>',
]

ICON_BTN_VALID_CONTENT_WITH_LINK = [
    '<Button asChild disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg" disabled>\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg">\n<Link href="https://example.com/">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Link>\n</Button>',
    '<Button asChild disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="secondary" size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="destructive" size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="outline" size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="ghost" size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link" size="sm">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg" disabled>\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
    '<Button asChild variant="link" size="lg">\n<Link href="https://example.com/">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Link>\n</Button>',
]

ICON_BTN_VALID_CONTENT_WITHOUT_LINK = [
    '<Button disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button >\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary" size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary" size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary" size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="secondary" size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive" size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive" size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive" size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="destructive" size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline" size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline" size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline" size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="outline" size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost" size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost" size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost" size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="ghost" size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link" size="sm" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link" size="sm">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link" size="lg" disabled>\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button variant="link" size="lg">\n<Loader className="mr-2 h-4 w-4"/>\ntest\n</Button>',
    '<Button disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button >\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary" size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary" size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary" size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="secondary" size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive" size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive" size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive" size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="destructive" size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline" size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline" size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline" size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="outline" size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost" size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost" size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost" size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="ghost" size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link" size="sm" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link" size="sm">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link" size="lg" disabled>\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
    '<Button variant="link" size="lg">\ntest\n<Loader className="mr-2 h-4 w-4"/>\n</Button>',
]
